# Generated by Django 5.1.3 on 2024-12-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_nickname', models.CharField(default=' ', max_length=100, primary_key=True, serialize=False)),
                ('cliente_nome', models.CharField(default=' ', max_length=180)),
                ('cliente_email', models.EmailField(default=' ', max_length=254)),
                ('cliente_idade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('funcionario_nickname', models.CharField(default=' ', max_length=100, primary_key=True, serialize=False)),
                ('funcionario_nome', models.CharField(default=' ', max_length=180)),
                ('funcionario_email', models.EmailField(default=' ', max_length=254)),
                ('funcionario_idade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_nickname', models.CharField(default=' ', max_length=100, primary_key=True, serialize=False)),
                ('pet_cliente', models.CharField(default=' ', max_length=180)),
                ('cliente_idade', models.IntegerField(default=0)),
            ],
        ),
    ]
