# Generated by Django 5.1.3 on 2024-12-13 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['cliente_nome'], 'verbose_name_plural': 'Clientes'},
        ),
    ]
