# Generated by Django 5.1.3 on 2024-12-13 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['pet_nome'], 'verbose_name_plural': 'Pets'},
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='cliente_idade',
            new_name='pet_idade',
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_nome',
            field=models.CharField(default=' ', max_length=180),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='api_rest.cliente'),
        ),
    ]
